version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: core-banking-postgres
    environment:
      POSTGRES_DB: orchestrator_db
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator_pwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: